PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, bio TEXT NOT NULL DEFAULT '', password TEXT NOT NULL, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
CREATE TABLE IF NOT EXISTS limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS skills (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, category TEXT NOT NULL, tags TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','published','hidden')), revision INTEGER NOT NULL, created INTEGER NOT NULL, updated INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS skills_discovery ON skills(status, updated);
CREATE INDEX IF NOT EXISTS skills_owner ON skills(owner_id);
CREATE TABLE IF NOT EXISTS versions (skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE, revision INTEGER NOT NULL, body TEXT NOT NULL, created INTEGER NOT NULL, PRIMARY KEY(skill_id, revision));
CREATE TRIGGER IF NOT EXISTS publish_initial AFTER INSERT ON skills WHEN NEW.status = 'published' BEGIN INSERT INTO versions VALUES(NEW.id, NEW.revision, NEW.body, NEW.updated); END;
CREATE TRIGGER IF NOT EXISTS publish_revision AFTER UPDATE OF revision ON skills WHEN NEW.status = 'published' BEGIN INSERT INTO versions VALUES(NEW.id, NEW.revision, NEW.body, NEW.updated); END;
CREATE TABLE IF NOT EXISTS favorites (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE, PRIMARY KEY(user_id,skill_id));
CREATE TABLE IF NOT EXISTS feedback (id TEXT PRIMARY KEY, skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id), kind TEXT NOT NULL CHECK(kind IN ('helpful','unfit','suggestion','case')), body TEXT NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS feedback_skill ON feedback(skill_id,created);
CREATE TABLE IF NOT EXISTS exchanges (id TEXT PRIMARY KEY, skill_id TEXT REFERENCES skills(id) ON DELETE SET NULL, sender TEXT NOT NULL REFERENCES users(id), recipient TEXT NOT NULL REFERENCES users(id), body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS exchanges_recipient ON exchanges(recipient);
CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, exchange_id TEXT NOT NULL REFERENCES exchanges(id) ON DELETE CASCADE, title TEXT NOT NULL, done INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS notifications (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, body TEXT NOT NULL, read INTEGER NOT NULL DEFAULT 0, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS notifications_user ON notifications(user_id,created);
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE, reporter TEXT NOT NULL REFERENCES users(id), reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', reviewer TEXT, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id), task_id TEXT, status TEXT NOT NULL, created INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_job ON jobs(skill_id) WHERE status IN ('creating','queued','running','unknown');
