'use client';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Compass, Search, X, Sprout, Heart } from 'lucide-react';
import { CATEGORY_NAMES } from '@/lib/model';
import { bilateralMatch, LINRAN_PROFILE, WEIGHTS } from '@/lib/bilateral-match';
import { useZoo, updateZoo } from '@/lib/zoo-store';
import { navigate } from '@/lib/navigation';
import { Avatar, Mascot, SkillCard, SkillIcon, Empty } from './primitives';

export function MatchExplanation() {
  const { state } = useZoo();
  const match = bilateralMatch({ supply: state.supply, demand: state.demand });
  return <div className="match-explanation"><p>{match.reason}</p><dl><dt>你的供给 / 需求</dt><dd>{state.supply.join('、') || '未填写'} / {state.demand.join('、') || '未填写'}</dd><dt>林然的供给 / 需求（示例）</dt><dd>{LINRAN_PROFILE.supply.join('、')} / {LINRAN_PROFILE.demand.join('、')}</dd></dl><div className="source-note">互补得分 = α·(Sᵢ·Dⱼ) + β·(Sⱼ·Dᵢ) − γ·(Sᵢ·Sⱼ)<br />α = {WEIGHTS.alpha}，β = {WEIGHTS.beta}，γ = {WEIGHTS.gamma}<br />供需向量按长度归一化；空向量按 0 处理。</div><dl><dt>你满足对方需求</dt><dd>{match.outbound.toFixed(3)} × 0.5</dd><dt>对方满足你的需求</dt><dd>{match.inbound.toFixed(3)} × 0.5</dd><dt>供给同质化扣分</dt><dd>{match.overlap.toFixed(3)} × 0.2</dd><dt>最终得分</dt><dd>{match.score} / 100</dd></dl><p className="small">加权结果截断到 0–1，再乘 100。用于演示排序，不是成功概率，也未做统计校准。</p><button className="outline" onClick={() => navigate('habitat')}>调整我的供给与需求 <ArrowRight size={16} /></button></div>;
}
export function Explore({ query, setQuery, explain }: { query: string; setQuery: (query: string) => void; explain: () => void }) {
  const { state } = useZoo();
  const [category, setCategory] = useState('全部栖息地');
  const [sort, setSort] = useState('为你发现');
  const match = bilateralMatch({ supply: state.supply, demand: state.demand });
  const normalized = query.trim().toLocaleLowerCase();
  let filtered = state.pool.filter(skill => (category === '全部栖息地' || skill.category === category) && [skill.title, skill.author, skill.desc, skill.tag].some(value => value.toLocaleLowerCase().includes(normalized)) && (sort !== '我的收藏' || state.saved.includes(skill.id)));
  if (sort === '最近生长') filtered = [...filtered].sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.id - a.id);
  return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> A LITTLE WILD. A LOT OF WISDOM.</div><h1>让经验长成 <em>Skill，</em><br />让 Skill 连接到<em>人。</em></h1><p>带着一个真实问题来，遇见可以一起生长的伙伴。<br />把各自擅长的事，变成一次具体的合作。</p><button className="primary" onClick={() => document.getElementById('problem-search')?.focus()}>带一个真实问题来 <ArrowUpRight size={17} /></button><div className="hero-community"><div className="avatar-stack"><Avatar name="林然" /><Avatar name="陈沐" color="peach" /><Avatar name="许知" color="lavender" /></div><span><b>{state.pool.length}</b> 个 Skill · 示例与本地成果</span></div></div><div className="hero-image kanshan-stage"><div className="kanshan-greeting"><span>你的探索伙伴</span><strong>嗨，我是刘看山。</strong><p>带上好奇心，我们一起出发！</p></div><Mascot pose="hello" className="hero-mascot" /><span className="art-label"><Sprout size={15} />刘看山 · 陪每一种经验生长</span></div><div className="hero-index">01 / EXPLORE YOUR POSSIBILITIES</div></section>
  <section className="discovery"><div className="discovery-search"><Search size={22} /><input id="problem-search" aria-label="搜索问题" placeholder="你最近在解决什么问题？" value={query} onChange={e => setQuery(e.target.value)} />{query && <button className="icon-btn" aria-label="清空搜索" onClick={() => setQuery('')}><X size={17} /></button>}<ArrowRight size={20} /></div><div className="categories">{['全部栖息地', ...CATEGORY_NAMES].map(name => <button className={category === name ? 'active' : ''} aria-pressed={category === name} key={name} onClick={() => setCategory(name)}>{name === '全部栖息地' ? <Compass size={17} /> : <SkillIcon category={name} size={17} />}{name}</button>)}</div></section>
  <div className="content-columns"><section className="main-column"><div className="section-head"><div><h2>发现正在生长的 Skill</h2><p>好的方法值得被看见，认真做事的人值得被认识。</p></div><span className="result-count">{filtered.length} 个新可能</span></div><div className="demo-tabs" aria-label="Skill 列表范围">{['为你发现', '最近生长', '我的收藏'].map(value => <button className={sort === value ? 'active' : ''} key={value} aria-pressed={sort === value} onClick={() => setSort(value)}>{value}</button>)}</div><div className="skill-grid">{filtered.map(skill => <SkillCard key={skill.id} skill={skill} saved={state.saved.includes(skill.id)} onOpen={() => navigate('explore', skill.id)} onSave={() => updateZoo(s => ({ ...s, saved: s.saved.includes(skill.id) ? s.saved.filter(id => id !== skill.id) : [...s.saved, skill.id] }))} />)}</div>{!filtered.length && <Empty title={sort === '我的收藏' ? '收藏夹还空着' : '还没有找到这颗种子'}><p>换一个关键词，或看看全部 Skill。</p><button className="outline" onClick={() => { setCategory('全部栖息地'); setQuery(''); setSort('为你发现'); }}>看看全部 Skill</button></Empty>}</section>
  <aside className="right-column"><section className="people-card"><div className="section-head"><h3>或许，你们会聊得来</h3><Heart size={16} /></div><div className="person"><Avatar name="林然" color="lavender" /><div><b>林然</b><small>城市研究博士生 · 示例作者</small></div></div><div className="match"><span>双边互补得分</span><strong>{match.score}<small> / 100</small></strong></div><p>{match.reason}</p><button className="text-button" onClick={explain}>为什么推荐给我 <ArrowRight size={16} /></button><button className="outline full" onClick={() => navigate('explore', 3)}>看看她的方法</button></section><section className="roam-card"><span className="eyebrow">CROSSING BOUNDARIES</span><h3>跨出熟悉的领域，<br />遇见新的可能。</h3><p>先写清你的能力与需求，再看看双方怎样补上彼此的缺口。</p><button className="text-button" onClick={() => navigate('habitat')}>完善我的供需 <ArrowRight size={16} /></button></section></aside></div></>;
}
